add operators for batch inference and add ability to refer on files b…
odahu/odahu-airflow-plugin pull request #28
Opened 2021-03-11 14:26 UTC by vlad-tokarev

Batch inference operators in plugin for https://github.com/odahu/odahu-flow/issues/500

2021-03-12 08:45 UTC, lev-titov approved these changes

2021-03-15 16:06 UTC, keshamin requested changes

2021-03-15 16:06 UTC, keshamin commented on odahuflow/airflow_plugin/batch.py
> +        context['task_instance'].xcom_push(key=XCOM_BATCH_ARTIFACT_KEY, value=batch.id)
I suppose, this is redundant because `batch.id` is also a return value of the `InferenceJobOperator`. Return values are automatically pushed to XCom with a key `'return_value'` (taken from constant `XCOM_RETURN_KEY`). 
Moreover, this constant is a default key for `.xcom_pull()` method, so pulling the batch ID in `InferenceJobSensor` can look like
```
batch_id = context['task_instance'].xcom_pull(task_ids=self.inference_job_task_id)
```

2021-03-15 16:06 UTC, keshamin commented on odahuflow/airflow_plugin/batch.py
> +    @apply_defaults
Is this a typo or I miss something? I mean the second decorator.

2021-03-16 10:23 UTC, karbyshevds approved these changes

2021-03-17 09:22 UTC, merged